/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IApproveAndCall__factory } from "./IApproveAndCall__factory";
export { IProxy__factory } from "./IProxy__factory";
